---
- name: Install VMware files
  copy:
    src: "{{ item }}"
    dest: "/Users/{{ ansible_user_id }}/code/vmware/"
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0600
  with_items:
    - p4.client

- name: Install VMware files
  copy:
    src: "{{ item }}"
    dest: "/Users/{{ ansible_user_id }}/code/vmware/"
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0700
  with_items:
    - sandbox.sh
    - update_toolchain.sh

- name: Install p4
  become: yes
  copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/"
    owner: "{{ ansible_user_id }}"
    group: admin
    mode: 0755
  with_items:
    - p4

- name: Install homebrew packages
  homebrew:
    name: "{{ vmware_homebrew_installed_packages }}"
    state: present
  when: homebrew_install|bool

- name: Add the taps
  homebrew_tap:
    tap: "{{ vmware_homebrew_taps }}"
    state: present
  when: homebrew_cask_install|bool

- name: Install homebrew-cask packages
  homebrew_cask:
    name: "{{ vmware_homebrew_cask_apps }}"
    state: present
  when: homebrew_cask_install|bool

- name: Upgrade homebrew packages
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: Upgrade homebrew-cask packages
  homebrew_cask:
    update_homebrew: yes
    upgrade_all: yes
