---
homebrew_install: true
homebrew_cask_install: true

vmware_homebrew_installed_packages:

vmware_homebrew_taps:
  - caskroom/versions

vmware_homebrew_cask_apps:
  - java8
  - intellij-idea-ce
  - microsoft-office
