- name: Uninstall applications
  become: yes
  ignore_errors: True
  file: path={{ item }} state=absent
  with_items:
    - "/Applications/Automator.app"
    - "/Applications/Calendar.app"
    - "/Applications/Chess.app"
    - "/Applications/Contacts.app"
    - "/Applications/DVD Player.app"
    - "/Applications/Dictionary.app"
    - "/Applications/Game Center.app"
    - "/Applications/Garageband.app"
    - "/Applications/Maps.app"
    - "/Applications/Photo Booth.app"
    - "/Applications/Photos.app"
    - "/Applications/Reminders.app"
    - "/Applications/Stickies.app"
    - "/Applications/iBooks.app"
    - "/Applications/iPhoto.app"

- name: Remove files
  become: yes
  ignore_errors: True
  file: path={{ item }} state=absent
  with_items:
    - "/Library/Dictionaries"
    - "/Library/Desktop Pictures"

- name: Remove voices
  become: yes
  ignore_errors: True
  file: path="/System/Library/Speech/Voices" state=absent
