# Tap.
- name: Always tap cask.
  homebrew_tap:
    tap: "homebrew/cask"
    state: present

- name: Add the taps
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items: "{{ homebrew_taps }}"

# Brew.
- name: Install homebrew packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_installed_packages }}"
  when: homebrew_install

# Cask.
- name: Install homebrew-cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_cask_apps }}"
  when: homebrew_cask_install

- name: Install homebrew-cask fonts
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_cask_fonts }}"
  when: homebrew_cask_fonts_install

# Upgrade
- name: Upgrade homebrew packages (if configured).
  homebrew:
    update_homebrew: yes
    upgrade_all: yes
  when: homebrew_upgrade_all_packages

- name: Upgrade homebrew-cask packages (if configured).
  homebrew_cask:
    update_homebrew: yes
    upgrade_all: yes
  when: homebrew_upgrade_all_packages
