---
homebrew_install: true
homebrew_cask_install: true
homebrew_upgrade_all_packages: true

homebrew_taps:
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/cask-versions
  - thoughtbot/formulae

homebrew_installed_packages:
  - autojump
  - awscli
  - bash
  - bash-completion
  - coreutils
  - curl
  - docker-completion
  - exa
  - exiftool
  - ffmpeg
  - gawk
  - gcc
  - git
  - gnupg
  - jq
  - kubectl
  - kubernetes-helm
  - minikube
  - nmap
  - openssl
  - pinentry-mac
  - pipenv
  - pstree
  - pyenv
  - python
  - rcm
  - ripgrep
  - terraform
  - the_silver_searcher
  - tree
  - vault
  - vim
  - watch
  - wget
  - ykman
  - youtube-dl
  - yubikey-personalization
  - zsh

homebrew_installed_packages_home:
  - dnscontrol
  - doctl
  - flarectl

homebrew_installed_packages_work:
  - lastpass-cli

homebrew_cask_apps:
  - 1password
  - docker
  - drawio
  - firefox
  - flux
  - google-cloud-sdk
  - gpg-suite
  - iterm2
  - licecap
  - menumeters
  - postman
  - slack
  - visual-studio-code
  - vmware-fusion
  - zoomus

homebrew_cask_apps_home:
  - doxie
  - do-not-disturb
  - knockknock
  - little-snitch
  - microsoft-office
  - netiquette
  - oversight
  - reikey
  - syncthing
  - taskexplorer
  - transmission
  - tunnelblick
  - vlc

homebrew_cask_apps_work:
  - lastpass

homedir_directories:
  - "/Users/{{ ansible_user_id }}/src"
  - "/Users/{{ ansible_user_id }}/src/sandbox"
  - "/Users/{{ ansible_user_id }}/src/github.com"
  - "/Users/{{ ansible_user_id }}/src/gitlab.com"

homedir_directories_work:
  - "/Users/{{ ansible_user_id }}/work"

homedir_directories_home:
  - "/Users/{{ ansible_user_id }}/src/gitlab.chinter.net"
  - "/Users/{{ ansible_user_id }}/sync/common"
  - "/Users/{{ ansible_user_id }}/sync/common/credentials/1password"
  - "/Users/{{ ansible_user_id }}/sync/personal"
  - "/Users/{{ ansible_user_id }}/sync/{{ host_name }}"