---
#- name: Clone vundle git repo
#  git: repo=https://github.com/gmarik/Vundle.vim.git dest="~/.vim/bundle/Vundle.vim"
#
#- name: Install vim plugins
#  command: vim +PluginInstall +qall

- name: Install iterm2 plist
  copy: src=com.googlecode.iterm2.plist dest="~/Library/Preferences/com.googlecode.iterm2.plist" mode=0600

- name: Load iterm2 plist
  shell: defaults read com.googlecode.iterm2

- name: Install mac-changer.sh
  copy: src=com.googlecode.iterm2.plist dest="/usr/local/bin" mode=0755

- name: Make directories in home
  file:
    path: "{{ item }}"
    state: directory
    mode: 0700
  with_items:
    - "{{ homedir_directories }}"
