---
- name: Configure MacOS defaults.
  hosts: all
  gather_facts: yes

  environment:
    HOMEBREW_NO_ANALYTICS: 1

  roles:
    - { role: system-config, hostname: "{{ host_name }}", lock_screen_message: "{{ lock_screen_message }}" }
