---
- name: Install Home
  hosts: all
  gather_facts: yes

  environment:
    HOMEBREW_NO_ANALYTICS: 1

  roles:
    - homebrew-common
    - home
    - customize
    - uninstall-apps
    - system-config