---
- name: Install Work
  hosts: all
  gather_facts: yes

  vars:
    host_name: 
    lock_screen_message:

  environment:
    HOMEBREW_NO_ANALYTICS: 1

  roles:
    - homebrew-common
    - work
    - customize
    - system-config